//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VTDI_Gate_Log1_flavaSolutions
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class VTDI_GLog_Db_EditedEntities1 : DbContext
    {
        public VTDI_GLog_Db_EditedEntities1()
            : base("name=VTDI_GLog_Db_EditedEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Color> Colors { get; set; }
        public virtual DbSet<GateLog> GateLogs { get; set; }
        public virtual DbSet<Gender> Genders { get; set; }
        public virtual DbSet<ItemsTo_Declare> ItemsTo_Declares { get; set; }
        public virtual DbSet<Purpose> Purposes { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<Vehicle_Type> Vehicle_Types { get; set; }
        public virtual DbSet<Visitor_Type> Visitor_Types { get; set; }
    }
}
